// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPctHO8Sb7FLBPn6F1eYVCqFnnHQS2y7E',
    appId: '1:91843799229:web:1c0064fe6a0da2b9b1efd4',
    messagingSenderId: '91843799229',
    projectId: 'bargain-hunter-1fe11',
    authDomain: 'bargain-hunter-1fe11.firebaseapp.com',
    storageBucket: 'bargain-hunter-1fe11.firebasestorage.app',
    measurementId: 'G-VCJ0NW40X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd16gVY1k9uYyyQhfeG2Xy_pHrAI_HtRg',
    appId: '1:91843799229:android:bfb3bcf77b7618b5b1efd4',
    messagingSenderId: '91843799229',
    projectId: 'bargain-hunter-1fe11',
    storageBucket: 'bargain-hunter-1fe11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgp_wILaIl4UICq-36Li7Q6bumurHtko',
    appId: '1:91843799229:ios:7e0fcfec3811adf8b1efd4',
    messagingSenderId: '91843799229',
    projectId: 'bargain-hunter-1fe11',
    storageBucket: 'bargain-hunter-1fe11.firebasestorage.app',
    iosBundleId: 'com.example.bargainHunter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhgp_wILaIl4UICq-36Li7Q6bumurHtko',
    appId: '1:91843799229:ios:7e0fcfec3811adf8b1efd4',
    messagingSenderId: '91843799229',
    projectId: 'bargain-hunter-1fe11',
    storageBucket: 'bargain-hunter-1fe11.firebasestorage.app',
    iosBundleId: 'com.example.bargainHunter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPctHO8Sb7FLBPn6F1eYVCqFnnHQS2y7E',
    appId: '1:91843799229:web:71c2e5a7e30e3fd3b1efd4',
    messagingSenderId: '91843799229',
    projectId: 'bargain-hunter-1fe11',
    authDomain: 'bargain-hunter-1fe11.firebaseapp.com',
    storageBucket: 'bargain-hunter-1fe11.firebasestorage.app',
    measurementId: 'G-Y9D5LKT8MG',
  );
}
